server:
  port: 8080

spring:
  rabbitmq:
    host: 192.168.0.29
    port: 5672
    username: guest
    password: guest
  application:
    name: hystrix-consumer-movie

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  port: 8990