spring:
  application:
    name: cluster-eureka-server-2

server:
  port: 8762

eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/ #设置 Eureka Server 交互的地址，查询服务和依赖服务都需要依赖这个地址，
                                                 # 多个地址使用“,”隔开