server:
  port: 8080

spring:
  application:
    name: hystrix-consumer-movie

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
