server:
  port: 8020

spring:
  application:
    name: eureka-consumer-movie


eureka:
  client:
    service-url:
      defaultZone: http://user:a123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
