server:
  port: 8020

spring:
  application:
    name: eureka-consumer-movie # \u6307\u5B9A\u6CE8\u518C\u5230 Eureka Server \u4E0A\u7684\u540D\u79F0


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true # \u8868\u793A\u5C06\u81EA\u5DF1\u7684IP\u6CE8\u518C\u5230 Eureka Server
